<?php
/**
 * Class Responsive_Theme_Options
 *
 * Responsive Theme Options
 *
 * Please do not edit this file. This file is part of the Responsive Framework and all modifications
 * should be made in a child theme.
 *
 * Class that extends Responsive_Options and supplies Theme with static methods to call
 *
 * @package        Responsive
 * @license        license.txt
 * @copyright      2014 CyberChimps
 * @since          2.0.0
 */

if ( !class_exists( 'Responsive_Theme_Options' ) ) {

	class Responsive_Theme_Options {

		public $sections;

		protected $options;

		protected $theme_options;

		protected static $get_options;

		public function __construct( $sections, $options ) {
			$this->sections           = $sections;
			$this->options   = $options;
			$this->theme_options = new Responsive_Options( $this->sections, $this->options );
			$get_options = $this->theme_options->get_parse_options();
		}

		public static function responsive_get_parse_options() {
			return self::$get_options;
		}
	}
}