<?php
/**
 * Template Name: Blog (full posts)
 *
 * Template for pages
 *
 * @package			${PACKAGE}
 * @license			license.txt
 * @copyright		${YEAR} ${COMPANY}
 * @since			${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}

get_header(); ?>

	<div id="content-blog" class="content-area">
		<div class="row">
			<main id="main" class="col-md-8" role="main">

				<?php get_template_part( 'loop-header' ); ?>

				<?php
				if ( get_query_var( 'paged' ) ) {
					$paged = get_query_var( 'paged' );
				} elseif ( get_query_var( 'page' ) ) {
					$paged = get_query_var( 'page' );
				} else {
					$paged = 1;
				}
				$blog_query = new WP_Query( array(
												'post_type' => 'post',
												'paged'     => $paged
											) );
				?>

				<?php if ( $blog_query->have_posts() ) : ?>

					<?php /* Start the Loop */ ?>
					<?php while ( $blog_query->have_posts() ) : $blog_query->the_post(); ?>

						<?php
						/* Include the Post-Format-specific template for the content.
						 * If you want to override this in a child theme, then include a file
						 * called content-___.php (where ___ is the Post Format name) and that will be used instead.
						 */
						get_template_part( 'content', get_post_format() );
						?>

					<?php endwhile; ?>

					<?php get_template_part( 'loop-nav' ); ?>

				<?php else : ?>

					<?php get_template_part( 'loop-no-posts' ); ?>

				<?php endif; ?>

				<?php wp_reset_postdata(); ?>

			</main>
			<!-- #main -->
			<?php get_sidebar(); ?>
		</div>
	</div><!-- #content-blog -->

<?php get_footer(); ?>