<?php
/**
 * Content Template
 *
 * Displays post content
 *
 * @package			${PACKAGE}
 * @license			license.txt
 * @copyright		${YEAR} ${COMPANY}
 * @since			${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}

responsive_entry_before(); ?>
	<article id="post-<?php the_ID(); ?>" <?php post_class(); ?> itemscope="itemscope" itemtype="http://schema.org/BlogPosting" itemprop="blogPost">
		<?php responsive_entry_top(); ?>

		<?php get_template_part( 'post-meta' ); ?>

		<div class="post-entry">
			<?php if ( is_search() || is_page_template( 'blog-excerpt.php' ) ) : // Only display Excerpts for Search ?>
				<div class="entry-summary">
					<?php the_excerpt(); ?>
				</div>
				<!-- .entry-summary -->
			<?php else : ?>
				<div class="entry-content">
					<?php if ( has_post_thumbnail() ) : ?>
						<div class="entry-thumbnail">
							<?php responsive_post_thumbnail(); ?>
						</div>
					<?php endif; ?>
					<?php the_content( __( 'Read more &#8250;', 'responsive' ) ); ?>
					<?php
					wp_link_pages( array(
									   'before' => '<div class="pagination">' . __( 'Pages:', 'responsive' ),
									   'after'  => '</div>',
								   ) );
					?>
				</div>
				<!-- .entry-content -->
			<?php endif; ?>
		</div>
		<!-- .post-entry -->

		<?php get_template_part( 'post-data' ); ?>

		<?php responsive_entry_bottom(); ?>
	</article>
	<!-- #post-## -->
<?php responsive_entry_after(); ?>