<?php
/**
 * Title
 *
 * Description
 *
 * @package            ${PACKAGE}
 * @license            license.txt
 * @copyright          ${YEAR} ${COMPANY}
 * @since              ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

$template_directory = get_template_directory();

/**
 * Theme Options
 */
require $template_directory . '/core/includes/theme-options/theme-options.php';
require $template_directory . '/core/includes/theme-options/theme-options-page.php';

/**
 * Basic theme functionality
*/
require $template_directory . '/core/includes/functions.php';

/**
 * Custom template tags for this theme.
 */
require $template_directory . '/core/includes/template-tags.php';

/**
 * Layout functions.
 */
require $template_directory . '/core/includes/functions-layout.php';

/**
 * Support THA Theme hooks through Responsives own functions.
 */
require $template_directory . '/core/includes/tha-theme-hooks.php';
require $template_directory . '/core/includes/responsive-hooks.php';

/**
 * Theme Upsell
 */
require $template_directory . '/core/includes/upsell/theme-upsell.php';

/**
 * Implement the Custom Header feature.
 */
require $template_directory . '/core/includes/custom-header.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-extras.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-front.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-menu.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-extentions.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-sidebar.php';

/**
 * Customizer additions.
 */
require $template_directory . '/core/includes/theme-options/customizer.php';

/**
 * Load Plugins compatibility file.
 */
require $template_directory . '/core/includes/functions-plugins.php';

/**
 * Load plugin dependency file.
 */
require $template_directory . '/core/includes/functions-install.php';
