<?php

// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) {
	exit;
}

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */

$template_directory = get_template_directory();

/**
 * Basic theme functionality
 */
require $template_directory . '/core/includes/functions.php';
/**
 * Theme Options
 */
require $template_directory . '/core/includes/theme-options/theme-options.php';
/**
 * Custom template tags for this theme.
 */
require $template_directory . '/core/includes/template-tags.php';
/**
 * Post layout functions.
 */
require $template_directory . '/core/includes/post-custom-layout.php';
/**
 * Support THA Theme hooks through Responsives own functions.
 */
require $template_directory . '/core/includes/tha-theme-hooks.php';
require $template_directory . '/core/includes/hooks.php';
/**
 * Fetch the current version info
 */
require $template_directory . '/core/includes/version.php';
/**
 * Theme Upsell
 */
require $template_directory . '/core/includes/upsell/theme-upsell.php';

/**
 * Implement the Custom Header feature.
 */
require $template_directory . '/core/includes/custom-header.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/extras.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-menu.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-plus.php';

/**
 * Custom functions that act independently of the theme templates.
 */
require $template_directory . '/core/includes/functions-sidebar.php';

/**
 * Customizer additions.
 */
require $template_directory . '/core/includes/theme-options/customizer.php';

/**
 * Load Jetpack compatibility file.
 */
require $template_directory . '/core/includes/jetpack.php';

// Return value of the supplied responsive free theme option.
function responsive_free_get_option( $option, $default = false ) {
	global $responsive_options;

	// If the option is set then return it's value, otherwise return false.
	if( isset( $responsive_options[$option] ) ) {
		return $responsive_options[$option];
	}

	return $default;
}
