<?php
/**
 * Page Meta
 *
 * Header information for the page
 *
 * @package            ${PACKAGE}
 * @license            license.txt
 * @copyright          ${YEAR} ${COMPANY}
 * @since              ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}
?>

<header class="entry-header">

	<!-- Display the page title if the toggle is on -->
	<?php if( get_post_meta( get_the_ID(), 'cyberchimps_page_title_toggle', true) ) { ?>
		<h1 class="entry-title post-title"><?php the_title(); ?></h1>
	<?php } ?>

	<?php if ( comments_open() ) : ?>
		<div class="post-meta">
			<?php responsive_posted_on(); ?>
			<?php responsive_post_meta_data(); ?>
			<?php if ( ! post_password_required() && ( comments_open() || '0' != get_comments_number() ) ) : ?>
				<span class="comments-link">
					<span class="mdash">&mdash;</span>
					<?php comments_popup_link( __( 'No Comments &darr;', 'responsive' ), __( '1 Comment &darr;', 'responsive' ), __( '% Comments &darr;', 'responsive' ) ); ?>
				</span>
			<?php endif; ?>
		</div><!-- .post-meta -->
	<?php endif; ?>
</header><!-- .entry-header -->