<?php
/**
 * Post Meta
 *
 * Displays the post title and meta data like posted on and comments
 *
 * @package			${PACKAGE}
 * @license			license.txt
 * @copyright		${YEAR} ${COMPANY}
 * @since			${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}
?>

<header class="entry-header">
	<?php if( is_single() ) : ?>
		<h1 class="entry-title post-title" itemprop="headline"><?php the_title(); ?></h1>
	<?php else: ?>
		<h2 class="entry-title post-title"><a href="<?php the_permalink(); ?>" rel="bookmark"><?php the_title(); ?></a></h2>
	<?php endif; ?>

	<?php if ( 'post' == get_post_type() ) : ?>
		<div class="post-meta">
			<?php responsive_post_meta_data(); ?>
			<?php responsive_posted_on(); ?>
			<?php if ( ! post_password_required() && ( comments_open() || '0' != get_comments_number() ) ) : ?>
				<span class="comments-link">
					<span class="mdash">&mdash;</span>
					<?php comments_popup_link( __( 'No Comments &darr;', 'responsive' ), __( '1 Comment &darr;', 'responsive' ), __( '% Comments &darr;', 'responsive' ) ); ?>
				</span>
			<?php endif; ?>
		</div><!-- .post-meta -->
	<?php endif; ?>
</header><!-- .entry-header -->
