<?php
/**
 * Search Template
 *
 * Displays search results
 *
 * @package			${PACKAGE}
 * @license			license.txt
 * @copyright		${YEAR} ${COMPANY}
 * @since			${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}

get_header(); ?>

	<div id="content-search" class="content-area">
		<div class="row">
			<main id="main" class="site-main col-md-8" role="main">

				<?php if ( have_posts() ) : ?>

					<?php get_template_part( 'loop-header' ); ?>

					<?php while ( have_posts() ) : the_post(); ?>

						<?php get_template_part( 'content', 'search' ); ?>

					<?php endwhile; ?>

					<?php get_template_part( 'loop-nav' ); ?>

				<?php else : ?>

					<?php get_template_part( 'loop-no-posts' ); ?>

				<?php endif; ?>

			</main>
			<!-- #main -->
			<?php get_sidebar(); ?>
		</div>
		<!-- row -->
	</div>
	<!-- #content-search -->
<?php get_footer(); ?>