<?php
/**
 * Colophon Sidebar
 *
 * Displays below the normal footer widgets and above the copyright text
 *
 * @package      Responsive_II
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the Responsive_II Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
	exit;
}

/*
 * If the sidebar is empty, exit
 */
if ( ! is_active_sidebar( 'colophon-widget' ) ) {
	return;
}
?>

<?php responsive_II_widgets_before(); ?>
<div id="colophon-widget" class="widget-area" role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
	<?php responsive_II_widgets(); ?>

		<?php dynamic_sidebar('colophon-widget'); ?>

	<?php responsive_II_widgets_end(); ?>
</div>
<!-- #colophon widget -->
<?php responsive_II_widgets_after(); ?>
