<?php
/**
 * Colophon Sidebar
 *
 * Displays below the normal footer widgets and above the copyright text
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/*
 * If the sidebar is empty, exit
 */
if ( ! is_active_sidebar( 'colophon-widget' ) ) {
	return;
}
?>

<?php responsive_mobile_widgets_before(); ?>
<div id="colophon-widget" class="widget-area" role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
	<?php responsive_mobile_widgets(); ?>

		<?php dynamic_sidebar('colophon-widget'); ?>

	<?php responsive_mobile_widgets_end(); ?>
</div>
<!-- #colophon widget -->
<?php responsive_mobile_widgets_after(); ?>
