<?php
/**
 * Default Sidebar
 *
 * @package            ${PACKAGE}
 * @license            license.txt
 * @copyright          ${YEAR} ${COMPANY}
 * @since              ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}
?>

<?php responsive_widgets_before(); ?>
<div id="widgets" class="widget-area col-md-4" role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
	<?php responsive_widgets(); ?>
	<?php if ( !dynamic_sidebar( 'main-sidebar' ) ) : ?>

		<aside id="archives" class="widget-wrapper">
			<h3 class="widget-title"><?php _e( 'In Archive', 'responsive' ); ?></h3>
			<ul>
				<?php wp_get_archives( array( 'type' => 'monthly' ) ); ?>
			</ul>
		</aside>

	<?php endif; // end sidebar widget area ?>
	<?php responsive_widgets_end(); ?>
</div>
<!-- #secondary -->
<?php responsive_widgets_after(); ?>
