<?php
/**
 * Gallery Sidebar
 *
 * Displays on the image page after clicking on a gallery image
 *
 * @package            ${PACKAGE}
 * @license            license.txt
 * @copyright        ${YEAR} ${COMPANY}
 * @since            ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) {
	exit;
}

if ( !is_active_sidebar( 'top-widget' )
) {
	return;
}
?>
<?php responsive_widgets_before(); // above widgets container hook ?>
	<div id="top-widget" class="top-widget" role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
		<?php responsive_widgets(); // above widgets hook ?>

			<?php dynamic_sidebar( 'top-widget' ); ?>

		<?php responsive_widgets_end(); // after widgets hook ?>
	</div><!-- end of #top-widget -->
<?php responsive_widgets_after(); // after widgets container hook ?>