<?php
/**
 * Title
 *
 * Description
 *
 * @package            ${PACKAGE}
 * @license            license.txt
 * @copyright          ${YEAR} ${COMPANY}
 * @since              ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

	<div id="content" class="content-area">
		<div class="row">
			<main id="main" class="site-main col-md-8" role="main">

				<?php while ( have_posts() ) : the_post(); ?>

					<?php get_template_part( 'content', 'single' ); ?>

					<?php responsive_comments_before(); ?>
					<?php
					// If comments are open or we have at least one comment, load up the comment template
					if ( comments_open() || '0' != get_comments_number() ) :
						comments_template( '', true );
					endif;
					?>
					<?php responsive_comments_after(); ?>

				<?php endwhile; // end of the loop. ?>

			</main>
			<!-- #main -->

			<?php get_sidebar(); ?>
		</div>
	</div><!-- #content -->
<?php get_footer(); ?>