<?php
/**
 * Responsive Dragable Class
 *
 * Creates dragable options created in Responsive_Options()
 *
 * @package      ${PACKAGE}
 * @license      license.txt
 * @copyright    ${YEAR} ${COMPANY}
 * @since        ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

class Responsive_Drag_Drop {
	
	public $items;
	
	public $drop_areas;
	
	public function __construct( $items = array(), $drop_areas = 1, $options ) {
		$this->items = $items;
		$this->drop_areas = $drop_areas;

		return $options;
	}

}