<?php
/**
 * Template Name: Blog Excerpt (summary)
 *
 * Template for pages
 *
 * @package            ${PACKAGE}
 * @license            license.txt
 * @copyright          ${YEAR} ${COMPANY}
 * @since              ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

get_header(); ?>

	<div id="content-blog-excerpt" class="content-area">
			<main id="main" role="main" itemprop="mainContentOfPage" itemscope="itemscope" itemtype="http://schema.org/Blog">

				<?php get_template_part( 'template-parts/loop-header' ); ?>

				<?php
				if ( get_query_var( 'paged' ) ) {
					$paged = get_query_var( 'paged' );
				}
				elseif ( get_query_var( 'page' ) ) {
					$paged = get_query_var( 'page' );
				}
				else {
					$paged = 1;
				}
				$blog_query = new WP_Query( array(
												'post_type' => 'post',
												'paged'     => $paged
											) );
				?>

				<?php if ( $blog_query->have_posts() ) : ?>

					<?php /* Start the Loop */ ?>
					<?php while ( $blog_query->have_posts() ) : $blog_query->the_post(); ?>

						<?php
						/* Include the Post-Format-specific template for the content.
						 * If you want to override this in a child theme, then include a file
						 * called content-___.php (where ___ is the Post Format name) and that will be used instead.
						 */
						get_template_part( 'template-parts/content', get_post_format() );
						?>

					<?php endwhile; ?>

					<?php get_template_part( 'template-parts/loop-nav' ); ?>

				<?php else : ?>

					<?php get_template_part( 'template-parts/loop-no-posts' ); ?>

				<?php endif; ?>

				<?php wp_reset_postdata(); ?>

			</main>
			<!-- #main -->
			<?php get_sidebar(); ?>
	</div>
	<!-- #content-blog -->

<?php get_footer(); ?>