<?php
/**
 * Functions Install
 *
 * Functions for installation & activation
 *
 * @package        Responsive
 * @license        license.txt
 * @copyright      2014 CyberChimps
 * @since          1.9.5.0
 *
 * Please do not edit this file. This file is part of the Responsive and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/*
 * Customize theme activation message.
 *
 * @since    1.9.5.0
 */
function responsive_activation_notice() {
	if ( isset( $_GET['activated'] ) ) {
		$return = '<div class="updated activation"><p><strong>';
					$my_theme = wp_get_theme();
		if ( isset( $_GET['previewed'] ) ) {
			$return .= sprintf( __( 'Settings saved and %s activated successfully.' ), $my_theme->get( 'Name' ) );
		} else {
			$return .= sprintf( __( '%s activated successfully.' ), $my_theme->get( 'Name' ) );
		}
		$return .= '</strong> <a href="' . home_url( '/' ) . '">' . __( 'Visit site', 'responsive' ) . '</a></p>';
		//$return .= '<p><a class="button button-primary customize load-customize" href="' . admin_url( 'customize.php?theme=' . get_stylesheet() ) . '">' . __( 'Customize', 'responsive' ) . '</a>';
		$return .= ' <a class="button button-primary theme-options" href="' . admin_url( 'themes.php?page=theme_options' ) . '">' . __( 'Theme Options', 'responsive' ) . '</a>';
		$return .= ' <a class="button button-primary help" href="https://cyberchimps.com/forum/free/responsive/">' . __( 'Help', 'responsive' ) . '</a>';
		$return .= '</p></div>';
		echo $return;
	}
}
add_action( 'admin_notices', 'responsive_activation_notice' );

/*
 * Hide core theme activation message.
 *
 * @since    1.9.5.0
 */
function responsive_admin_css() { ?>
	<style>
	.themes-php #message2 {
		display: none;
	}
	.themes-php div.activation a {
		text-decoration: none;
	}
	</style>
<?php }
add_action( 'admin_head', 'responsive_admin_css' );

/**
 * Add plugin automation file
 */
if ( ! class_exists( 'Theme_Plugin_Dependency' ) ) {
	require_once( dirname( __FILE__ ) . '/classes/class-theme-plugin-dependency.php' );
}

/**
 * Ignore admin notice
 *
 * @since     2.0.0
 */
function responsive_ignore_notice() {
	$current_user = wp_get_current_user();
	$user_id = $current_user->ID;
	/* If user clicks to ignore the notice, add that to their user meta */
	if ( isset( $_GET[ 'responsive_ignore_notice'] ) && 'true' == $_GET[ 'responsive_ignore_notice'] ) {
		update_user_meta( $user_id, 'responsive_ignore_notice', 'true' );
	}
	if ( isset( $_GET[ 'responsive_ignore_notice'] ) && 'false' == $_GET[ 'responsive_ignore_notice'] ) {
		delete_user_meta( $user_id, 'responsive_ignore_notice' );
	}
}
add_action( 'admin_init', 'responsive_ignore_notice' );

/*
 * Add notification to Reading Settings page to notify if Custom Front Page is enabled.
 *
 * @since    1.9.4.0
 */
// @TODO link to plugin as info.
function responsive_plugin_notice() {
	global $pagenow;
	$current_user = wp_get_current_user();
	$user_id = $current_user->ID;
	// Check that the user hasn't already clicked to ignore the message
	// Add plugin notification only if the current user ican install plugins and on theme.php
	if ( ! get_user_meta( $user_id, 'responsive_ignore_notice' ) && current_user_can( 'install_plugins' ) && 'themes.php' == $pagenow ) {

		$responsive_add_ons = new Theme_Plugin_Dependency( 'responsive-add-ons', 'http://wordpress.org/plugins/responsive-add-ons/' );
		$msg .= '<p>' . sprintf(
			/* Translators: Responsive recommends using Responsive Add Ons. */
			__( 'Responsive recommends using %1$s.', 'responsive' ),
			'<a href="' . esc_url( 'http://wordpress.org/plugins/responsive-add-ons/' ) . '">' . __( 'Responsive Add Ons', 'responsive' ) . '</a>'
		) . '</p>';
		if ( $responsive_add_ons->check_active() ) {
			$msg .= sprintf(
					/* Translators: Responsive Add Ons is installed and activated! */
					__( '%1$s is installed and activated!', 'responsive' ),
					'<a href="' . esc_url( 'http://wordpress.org/plugins/responsive-add-ons/' ) . '">' . __( 'Responsive Add Ons', 'responsive' ) . '</a>'
				);
		} elseif ( $responsive_add_ons->check() ) {
			$msg .= sprintf(
					/* Translators: Responsive Add Ons is installed, but not activated. */
					__( '%1$s is installed, but not activated.', 'responsive' ),
					'<a href="' . esc_url( 'http://wordpress.org/plugins/responsive-add-ons/' ) . '">' . __( 'Responsive Add Ons', 'responsive' ) . '</a>'
				);
			$msg .= '</p><p><a href="' . $responsive_add_ons->activate_link() . '">' . __( 'Activate Responsive Add Ons', 'responsive' ) . '</a>';
		} elseif ( $install_link = $responsive_add_ons->install_link() ) {
			$msg .= sprintf(
					/* Translators: Responsive Add Ons is not installed. */
					__( '%1$s is not installed.', 'responsive' ),
					'<a href="' . esc_url( 'http://wordpress.org/plugins/responsive-add-ons/' ) . '">' . __( 'Responsive Add Ons', 'responsive' ) . '</a>'
				);
			$msg .= '</p><p><a href="' . $install_link . '">' . __( 'Install Responsive Add Ons', 'responsive' ) . '</a>';
		} else {
			$msg .= __( 'Responsive Add Ons is not installed. Please install this plugin manually.', 'responsive' );
		}
		$msg .= ' | <a href="?responsive_ignore_notice=true">' . __( 'Hide Notice' ) . '</a>';
		$return = '<div class="updated"><p>';
		$return .= $msg;
		$return .= '</p></div>';

		echo $return;
	}

}


add_action( 'admin_notices', 'responsive_plugin_notice' );
