<?php
/**
 * Menu
 *
 * Extra menu settings
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Get our wp_nav_menu() fallback, wp_page_menu(), to show a home link.
 *
 * @param array $args Configuration arguments.
 * @return array
 */
function responsive_mobile_page_menu_args( $args ) {
	$args['show_home'] = true;
	$args['menu_class'] = 'main-nav';
	return $args;
}
add_filter( 'wp_page_menu_args', 'responsive_mobile_page_menu_args' );
