<?php
/**
 * Meta Box Options
 *
 * Meta Box Options for pages
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Exit if accessed directly
if( !defined( 'ABSPATH' ) ) {
	exit;
}

// @TODO Place within function

if( is_admin() ) {

	/*********************************** PAGE OPTIONS STARTS ******************************************/
	$fields = array( 
		array(
			'type'  => 'checkbox',
			'id'    => 'cyberchimps_page_title_toggle',
			'class' => 'checkbox',
			'name'  => __( 'Page Title', 'responsive' ),
			'std'   => 1
		),
		
		
	);
	/*
	 * configure your meta box
	 */
	$config = array(
		'id'             => 'cyberchimps_page_options', // meta box id, unique per meta box
		'title'          => __( 'Page Options', 'responsive' ), // meta box title
		'pages'          => array( 'page' ), // post types, accept custom post types as well, default is array('post'); optional
		'context'        => 'normal', // where the meta box appear: normal (default), advanced, side; optional
		'priority'       => 'high', // order of meta box: high (default), low; optional
		'fields'         => $fields, // list of meta fields (can be added by field arrays)
		'local_images'   => false, // Use local or hosted images (meta box images for add/remove)
		'use_with_theme' => true //change path if used with theme set to true, false for a plugin or anything else for a custom path(default false).
	);

	/*
	 * Initiate your meta box
	 */
	$my_meta = new Cyberchimps_Meta_Box( $config );
	/************************************ PAGE OPTIONS ENDS ***************************************/
}