<?php
/**
 * Plugin Support
 *
 * Support for Jetpack & WooCommerce
 *
 * @package      ${PACKAGE}
 * @license      license.txt
 * @copyright    ${YEAR} ${COMPANY}
 * @since        ${VERSION}
 *
 * Please do not edit this file. This file is part of the ${PACKAGE} Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Add theme support for Infinite Scroll.
 * See: http://jetpack.me/support/infinite-scroll/
 */
function responsive_jetpack_setup() {
	add_theme_support( 'infinite-scroll', array(
		'container' => 'main',
		'footer'    => 'page',
	) );
}
add_action( 'after_setup_theme', 'responsive_jetpack_setup' );

/**
 * WooCommerce
 *
 * Unhook/Hook the WooCommerce Wrappers
 */
// @TODO Fix grid system
function responsive_woocommerce_wrapper() {
	echo '<div id="content-woocommerce" class="content-area"><main id="main" class="site-main" role="main">';
}
remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
add_action( 'woocommerce_before_main_content', 'responsive_woocommerce_wrapper', 10 );

function responsive_woocommerce_wrapper_end() {
	echo '</main><!-- #main -->';
}
remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );
add_action( 'woocommerce_after_main_content', 'responsive_woocommerce_wrapper_end', 10 );

function responsive_woocommerce_content_end() {
	echo '</div><!-- #content-woocommerce -->';
}
add_action( 'woocommerce_sidebar', 'responsive_woocommerce_content_end', 9 );
